  include "floors.asm"
  include "doors.asm"
  include "beds.asm"
  include "chairs.asm"
  include "tables.asm"
  include "walls.asm"
  include "soft_walls.asm"
  include "computers.asm"
  include "shards.asm"
  include "trash.asm"
  include "pda.asm"
  include "body.asm"
  include "electronic.asm"
  include "plants.asm"
  include "keramit.asm"
  include "grass.asm"
  include "airland.asm"
  include "scafs.asm"
  
  